import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/common/Provider";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/common/Header";
import PrelineScript from "@/components/common/PrelineScript";

export const metadata: Metadata = {
  title: "Greenworks Tools Dev - Headless",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
    <Provider>
      <body className={inter.className}>  
      
        <Header />
            {children}    
     
      </body>   
      <PrelineScript />  
      </Provider>    
    </html>
  );
}
